<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.weakref</groupId>
        <artifactId>nitro-parent</artifactId>
        <version>1-SNAPSHOT</version>
    </parent>

    <artifactId>nitro-engine</artifactId>
    <name>nitro-engine</name>
    <description>Nitro evaluation engine</description>

    <dependencies>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </dependency>

        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
            <version>8.5.18</version>
        </dependency>
        <dependency>
            <groupId>org.weakref</groupId>
            <artifactId>nitro-spi</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

</project>
